engines:
  duplications:
    enabled: true
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    config:
      extensions:
      - .es6
      - .js
      - .jsx
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/"
languages:
  JavaScript: true
exclude_paths:
- "src/coverage"
- "src/helpers/"
- "src/tests"
- .gitignore
- .eslintignore
- .travis.yml