dist: trusty
language: node_js

node_js:
  - node
  - 6

services:
  - postgresql

before_script:
  - npm install
  - npm install -g sequelize-cli
  - npm install sequelize
  - psql -c 'create database docmanager_test;' -U postgres
  - sudo -u postgres createuser kingisaac95
  - npm run migrate:test

script:
  - npm test
