dist: trusty
language: node_js

node_js:
  - node
  - 6

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE docmanager_test;' -U postgres
  - psql -c 'CREATE USER kingisaac95 WITH PASSWORD null;' -U postgres

script:
  - npm run migrate:test
  - npm test
