dist: trusty
language: node_js

node_js:
  - node
  - 6

services:
  - postgresql

before_script:
  - sudo -u postgres createuser kingisaac95
  - psql -c 'create database docmanager_test;' -U postgres

script:
  npm migrate
  npm migrate:test
  npm test