dist: trusty
language: node_js

node_js:
  - node
  - 6

services:
  - postgresql

before_script:
  - npm install
  - npm install sequelize
  - npm install -g sequelize-cli
  - sudo -c postgres createuser kingisaac95
  - psql createdb docmanager_test

script:
  - npm run migrate
  - npm test
