dist: trusty
language: node_js

node_js:
  - node
  - 6

services:
  - postgresql

before_script:
  - npm install
  - npm install -g sequelize-cli
  - sudo -u postgres createuser kingisaac95
  - createdb docmanager_test
  - npm run migrate:test

script:
  - npm test
