sudo: required
dist: trusty
language: node_js

node_js:
  - 6
 
before_script:
  - nvm install 6
  - npm install
  - npm install -g sequelize-cli
  - psql -c 'create database docmanager-test;' -U postgres
  - sudo -u postgres createuser kingisaac95

script:
  - npm test
